name: Add Author Info and FOO to PR Description
on:
    pull_request_review:
        types: [submitted]

permissions:
  pull-requests: write
  contents: read

jobs:
  add-info:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get all reviews
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            // Get unique reviewers who have submitted reviews
            const uniqueReviewers = new Set();
            const reviewerDetails = [];

            for (const review of reviews.data) {
              if (!uniqueReviewers.has(review.user.login)) {
                uniqueReviewers.add(review.user.login);
                const reviewerData = await github.rest.users.getByUsername({
                  username: review.user.login
                });
                reviewerDetails.push(reviewerData.data);
              }
            }

            // Build reviewer info section
            let reviewerInfo = '';
            if (reviewerDetails.length > 0) {
              reviewerInfo = '\n**Reviewers:**\n';
              for (const reviewer of reviewerDetails) {
                reviewerInfo += `${reviewer.login} ${reviewer.name || 'Not provided'}`;
              }
              reviewerInfo += '\n---\n';
            }
            
            const updatedBody = `${pr.data.body || ''}\n\n${reviewerInfo}`;
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: updatedBody
            });
