name: Add Author Info and FOO to PR Description
on:
    pull_request_review:
        types: [submitted]

permissions:
  pull-requests: write
  contents: read

jobs:
  add-info:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            let updatedBody = `${pr.data.body}`;
            if (context.eventName === 'pull_request_review' && context.payload.review.state === 'APPROVED') {
              const reviewer = context.payload.review.user;
              const reviewerDetails = await github.rest.users.getByUsername({
                username: reviewer.login
              });

              // Get reviewer's recent commits to fetch email
              const recentCommits = await github.rest.repos.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                author: reviewer.login,
                per_page: 1
              });

              const reviewerEmail = recentCommits.data[0]?.commit?.author?.email || 'Not available';
              
                const reviewerInfo = `
                Approved by: ${reviewerDetails.data.name || 'Name not provided'} <${reviewerEmail}>(@${reviewer.login})
                `;
                
                updatedBody = `${pr.data.body || ''}\n\n${reviewerInfo}`;
            }
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: updatedBody
            });
