name: Add Author Info and FOO to PR Description
on:
    pull_request_review:
        types: [submitted]

permissions:
  pull-requests: write
  contents: read

jobs:
  add-info:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            // Get all reviews
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            // Get unique reviewers who have approved the PR
            const uniqueReviewers = new Set();
            const reviewerDetails = [];

            // Process reviews in chronological order (oldest first)
            // This way we'll get the most recent state for each reviewer
            for (const review of reviews.data) {
              if (review.state === 'APPROVED') {
                uniqueReviewers.add(review.user.login);
              } else if (review.state !== 'COMMENTED') {
                // Remove reviewer if they changed their mind (dismissed or requested changes)
                uniqueReviewers.delete(review.user.login);
              }
            }

            // Fetch details for approved reviewers
            for (const reviewerLogin of uniqueReviewers) {
              const reviewerData = await github.rest.users.getByUsername({
                username: reviewerLogin
              });
              reviewerDetails.push(reviewerData.data);
            }

            // Build reviewer info section
            let reviewerInfo = '';
            if (reviewerDetails.length > 0) {
              reviewerInfo = '\n**Reviewers:**\n';
              for (const reviewer of reviewerDetails) {
                reviewerInfo += `${reviewer.login} ${reviewer.name || 'Not provided'}`;
              }
              reviewerInfo += '\n---\n';
            }
            
            const updatedBody = `${pr.data.body || ''}\n\n${reviewerInfo}`;
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: updatedBody
            });
