name: Add Author Info and FOO to PR Description
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  add-info:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            // Fetch complete user details
            const userDetails = await github.rest.users.getByUsername({
              username: pr.data.user.login
            });
            
            const authorInfo = `
            **Author Information:**
            - Name: ${userDetails.data.name || 'Not provided'}
            - Login: @${pr.data.user.login}
            
            ---
            `;
            
            const updatedBody = `${pr.data.body || ''}\n\n${authorInfo}`;
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: updatedBody
            });
